name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, repositories

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-languages.svg
          plugin_languages: yes

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-streaks.svg
          plugin_streaks: yes

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-trophies.svg
          plugin_trophies: yes

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-calendar.svg
          plugin_calendar: yes
    
     
      - uses: lowlighter/metrics@latest
        with:
         token: ${{ secrets.METRICS_TOKEN }}
         filename: github-metrics.svg
         base: header, activity
         plugin_languages: yes
         plugin_calendar: yes
         plugin_isocalendar: yes
